const jogar = confirm('Bem-vindo(a) ao nosso mundo Barbie!')
alert('Quem você seria em Barbie?')
prompt('Escolha uma cor: Rosa, Rosachoc, Azul, Roxo')
prompt('Escolha um estilo musical: Gospel, Eletronico, Pagode, Funk')
prompt('Qual animal você mais gosta? Gato, Passaro, Cachorro, Urso')
prompt('Qual seu maior medo? Escuro, Monstros, Perder um familiar, Baratas')
prompt('Qual seu sonho de vida?')
alert('PARABÉNSSS🎆🎀💗')
alert('você seria...')
alert('BARBIEEEEEE🎆🎀🎆🎀🎆🎀')
